name: prepare-env
description: Prepares Envionrment

runs:
  using: 'composite'

  steps:
    - name: Setup Node
      uses: actions/setup-node@v3.5.1
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
        cache: 'yarn'
        cache-dependency-path: |
          .yarn/cache
          .pnp.*
      run: corepack enable
      run: yarn install --immutable

    - name: Configure git
      run: |
        git config --global user.name a11y-react
        git config --global user.email imccausl@gmail.com
        git config --global init.defaultBranch main
      shell: bash
