name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  ARTIFACTS_DIR: ./artifacts

jobs:
  commit-watch:
    runs-on: ubuntu-latest
    if: "github.event_name == 'pull_request'"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Commit Watch
        env:
          COMMIT_WATCH_OUTPUT_DIR: ${{ env.ARTIFACTS_DIR }}
          COMMITWATCH_GITHUB_TOKEN: ${{ secrets.PR_BOT_GITHUB_TOKEN }}
          CI_REPO_OWNER: ${{ github.repository_owner }}
          CI_REPO_NAME: ${{ github.event.repository.name }}
          CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          CI_BASE_BRANCH: origin/${{ github.base_ref }}
        run: yarn dlx commit-watch

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Build packages
        run: yarn prepack

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Run Tests
        run: yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Run ESLint
        run: yarn lint

  types:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Check Types
        run: yarn typecheck
