name: Deploy & Publish

on:
  workflow_run:
    workflows: ['Continuous Integration']
    paths:
      - '**/packages/**/*'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARTIFACTS_DIR: ./artifacts
  CI: 1

jobs:
  pre-release-check:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
      - name: Build packages
        run: yarn prepack
      - name: Run Tests
        run: yarn test

  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    needs: [pre-release-check]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-env
      - name: Publish Packages
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn monodeploy --log-level 0 --config-file monodeploy.config.js --push

  deploy-storybook:
    name: Build & Deploy Storybook
    runs-on: ubuntu-latest
    needs: [pre-release-check]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-env
      - run: yarn docs:deploy
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
